apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxweather-deployment
  namespace: nginx-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maxweather-app
  template:
    metadata:
      labels:
        app: maxweather-app
    spec:
      containers:
      - name: maxweather-app
        image: sajeeval/myawesomeapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: maxweather-app-svc
  namespace: nginx-ingress
spec:
  selector:
    app: maxweather-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      name: http
#  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maxweather-ingress
  namespace: nginx-ingress
spec:
  rules:
#  - host: maxweather.com 
   - http:
      paths:
      - path: /
        backend:
          serviceName: maxweather-app-svc
          servicePort: 8085